UserInterface:
  splash_screen: 'loading.jpg'
  progress_bar:
      x_center: 0.5
      y_center: 0.25
      width: 0.9
      height: 0.10
      border: 
        - 255
        - 0
        - 255
      fill: 
        - 0
        - 255
        - 0
  text:
    y_center: 0.3
LampShows:
- key: 'attract_show_1'
  file: 'attract_show_1.lampshow'  
- key: 'attract_show_2'
  file: 'attract_show_2.lampshow'  
Animations:
- key: 'cows'
  file: 'cows_shuffling.dmd'  
- key: 'firework'
  file: 'firework.dmd'  
  composite_op: 'greensrc'
  x_loc: 100
  y_loc: 0
- key: 't800-war'
  file: 't800-war_one.gif'
  frame_time : 2
- key: 'explosion'
  file: 'explosion.gif'
  frame_time : 4
  composite_op: 'magentasrc'  
- key: 'gameover'
  file: 'thumbsup.gif'
  frame_time : 2
- key: 'chrome'
  file: 'chrome.png'  
- key: 'dark_chrome'
  file: 'dark_chrome.png'  
- key : 'title'
- key : 'fire'
- key : 'pretty'
- key : 'flames'
  frame_time : 3
  repeatAnim : True
  # y_loc: -30
Fonts:
  FontStyles:
  - key: weird
    interior_color:
      - 0
      - 0
      - 128
    line_width: 1
    line_color:
      - 255
      - 0
      - 128
  FontStyles:
  - key: blueish
    interior_color:
      - 0
      - 0
      - 255
    line_width: 1
    line_color:
      - 0
      - 0
      - 128
  HDFonts:
  - key: 'Tiny7'
    systemName: "Arial"
    size: 14
  - key: 'Font_7x5'
    systemName: "Times"
    size: 14
  - key: 'Font_14x10'
    systemName: "Consolas"
    size: 20
  - key: 'SM20aa'
    systemName: "Consolas"
    size: 20
  - key: 'mono-tiny'
    systemName: "Consolas"
    size: 18
  - key: 'mono-micro'
    systemName: "Consolas"
    size: 12
  - key: 'Arrows'
    systemName: "Roadgeek 2005 Arrows 1"
    size: 24
  - key: 'settings-font'
    systemName: "H.H. Samuel"
    size: 16
  - key: 'settings-font-small'
    systemName: "H.H. Samuel"
    size: 15
  - key: 'tiny'
    systemName: "H.H. Samuel"
    size: 8
  - key: 'small'
    systemName: "H.H. Samuel"
    size: 12
  - key: 'med'
    systemName: "H.H. Samuel"
    size: 15
  - key: 'large'
    systemName: "Terminator Two"
    size: 20
  - key: 'score_1p'
    systemName: "H.H. Samuel"
    size: 48
  - key: 'score_activeL'
    systemName: "H.H. Samuel"
    size: 48
  - key: 'score_activeM'
    systemName: "H.H. Samuel"
    size: 40
  - key: 'score_activeS'
    systemName: "H.H. Samuel"
    size: 32
  - key: 'score_inactive'
    systemName: "H.H. Samuel"
    size: 32
  - key: 'score_sub'
    systemName: "Terminator Two"
    size: 14
  - key: 'default_msg'
    systemName: "H.H. Samuel"
    size: 15
  - key: 'tilt-font-small'
    systemName: "H.H. Samuel"
    size: 15
  - key: 'tilt-font-big'
    systemName: "H.H. Samuel"
    size: 18
  - key: 'high_score_entry_inits'
    systemName: "consolas"
    size: 12
  - key: 'high_score_entry_msg'
    systemName: "consolas"
    size: 12
  - key: 'high_score_entry_letters'
    systemName: "consolas"
    size: 12
  DMDFonts:
  - key: 'CC_9px'
    file: "Font_CC_9px_az.dmd"
  - key: 'font_matrix'
    file: "switch_matrix_font.dmd"
Audio:
  Music:
    - key: 'base-music-bgm'
      file: 'BufThmS3.wav'
      volume: 0.1
    - key: 'canon'
      file: 'Cannon.ogg'         
  Effects:
    - key: 'ball_serve'
      file: 'BallServe.ogg'
    - key: 'ball_launch'
      file: 'ballServed.ogg'
    - key: 'ball_saved'
      file: 'AutoFire.ogg'
    - key: 'ball_saved'
      file: 'AutoFire.ogg'
    - key: 'ss_tick'
      file: 'skill_shot_target_move.ogg'
    - key: 'ss_hit'
      file: 'TargetHit.ogg'
    - key: 'ss_miss'
      file: 'ss_miss.ogg'
    - key: 'service_save'
      file: 'save.wav'
    - key: 'service_previous'
      file: 'previous_item.wav'
    - key: 'service_enter'
      file: 'menu_in.wav'
    - key: 'service_exit'
      file: 'menu_out.wav'
    - key: 'service_next'
      file: 'next_item.wav'
    - key: 'service_cancel'
      file: 'menu_out.wav'
    - key: 'sling'
      file: 'sling1.ogg'
    - key: 'sling'
      file: 'sling2.ogg'   
    - key: 'target'
      file: 'randomTarget1.ogg'   
    - key: 'target'
      file: 'randomTarget2.ogg'   
    - key: 'target'
      file: 'randomTarget3.ogg'   
  Voice:
    - key: 'ss_successV'
      file: 'DirectHit1.ogg'
      volume: 0.8
    - key: 'ss_missV'
      file: 'YouMissed2.ogg'
      volume: 0.8
